/* The following code was generated by JFlex 1.7.0 */

/*
    This file will be a lot less commented because this is esentially copy-paste rules from our
	last project.
*/


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>nanoMorpho.jflex</tt>
 */
public class NanoMorphoLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\37\1\41\1\42\1\40\22\0\1\43\1\23\1\5"+
    "\2\0\1\23\1\20\1\14\2\17\1\23\1\4\1\17\1\4\1\2"+
    "\1\23\4\15\4\16\2\1\1\23\1\36\1\23\1\24\2\23\1\0"+
    "\4\22\1\3\25\22\1\0\1\6\1\0\1\23\1\22\1\0\1\30"+
    "\1\7\2\22\1\27\1\12\1\22\1\34\1\32\2\22\1\26\1\22"+
    "\1\11\3\22\1\13\1\31\1\10\1\25\1\35\1\33\3\22\1\17"+
    "\1\21\1\17\1\23\6\0\1\41\44\0\1\22\12\0\1\22\4\0"+
    "\1\22\5\0\27\22\1\0\37\22\1\0\u01ca\22\4\0\14\22\16\0"+
    "\5\22\7\0\1\22\1\0\1\22\201\0\5\22\1\0\2\22\2\0"+
    "\4\22\1\0\1\22\6\0\1\22\1\0\3\22\1\0\1\22\1\0"+
    "\24\22\1\0\123\22\1\0\213\22\10\0\246\22\1\0\46\22\2\0"+
    "\1\22\7\0\47\22\110\0\33\22\5\0\3\22\55\0\53\22\43\0"+
    "\2\22\1\0\143\22\1\0\1\22\17\0\2\22\7\0\2\22\12\0"+
    "\3\22\2\0\1\22\20\0\1\22\1\0\36\22\35\0\131\22\13\0"+
    "\1\22\30\0\41\22\11\0\2\22\4\0\1\22\5\0\26\22\4\0"+
    "\1\22\11\0\1\22\3\0\1\22\27\0\31\22\107\0\25\22\1\0"+
    "\10\22\106\0\66\22\3\0\1\22\22\0\1\22\7\0\12\22\17\0"+
    "\20\22\4\0\10\22\2\0\2\22\2\0\26\22\1\0\7\22\1\0"+
    "\1\22\3\0\4\22\3\0\1\22\20\0\1\22\15\0\2\22\1\0"+
    "\3\22\16\0\2\22\23\0\6\22\4\0\2\22\2\0\26\22\1\0"+
    "\7\22\1\0\2\22\1\0\2\22\1\0\2\22\37\0\4\22\1\0"+
    "\1\22\23\0\3\22\20\0\11\22\1\0\3\22\1\0\26\22\1\0"+
    "\7\22\1\0\2\22\1\0\5\22\3\0\1\22\22\0\1\22\17\0"+
    "\2\22\27\0\1\22\13\0\10\22\2\0\2\22\2\0\26\22\1\0"+
    "\7\22\1\0\2\22\1\0\5\22\3\0\1\22\36\0\2\22\1\0"+
    "\3\22\17\0\1\22\21\0\1\22\1\0\6\22\3\0\3\22\1\0"+
    "\4\22\3\0\2\22\1\0\1\22\1\0\2\22\3\0\2\22\3\0"+
    "\3\22\3\0\14\22\26\0\1\22\64\0\10\22\1\0\3\22\1\0"+
    "\27\22\1\0\20\22\3\0\1\22\32\0\3\22\5\0\2\22\36\0"+
    "\1\22\4\0\10\22\1\0\3\22\1\0\27\22\1\0\12\22\1\0"+
    "\5\22\3\0\1\22\40\0\1\22\1\0\2\22\17\0\2\22\22\0"+
    "\10\22\1\0\3\22\1\0\51\22\2\0\1\22\20\0\1\22\5\0"+
    "\3\22\10\0\3\22\30\0\6\22\5\0\22\22\3\0\30\22\1\0"+
    "\11\22\1\0\1\22\2\0\7\22\72\0\60\22\1\0\2\22\14\0"+
    "\7\22\72\0\2\22\1\0\1\22\2\0\2\22\1\0\1\22\2\0"+
    "\1\22\6\0\4\22\1\0\7\22\1\0\3\22\1\0\1\22\1\0"+
    "\1\22\2\0\2\22\1\0\4\22\1\0\2\22\11\0\1\22\2\0"+
    "\5\22\1\0\1\22\25\0\4\22\40\0\1\22\77\0\10\22\1\0"+
    "\44\22\33\0\5\22\163\0\53\22\24\0\1\22\20\0\6\22\4\0"+
    "\4\22\3\0\1\22\3\0\2\22\7\0\3\22\4\0\15\22\14\0"+
    "\1\22\21\0\46\22\1\0\1\22\5\0\1\22\2\0\53\22\1\0"+
    "\u014d\22\1\0\4\22\2\0\7\22\1\0\1\22\1\0\4\22\2\0"+
    "\51\22\1\0\4\22\2\0\41\22\1\0\4\22\2\0\7\22\1\0"+
    "\1\22\1\0\4\22\2\0\17\22\1\0\71\22\1\0\4\22\2\0"+
    "\103\22\45\0\20\22\20\0\126\22\2\0\6\22\3\0\u026c\22\2\0"+
    "\21\22\1\0\32\22\5\0\113\22\6\0\10\22\7\0\15\22\1\0"+
    "\4\22\16\0\22\22\16\0\22\22\16\0\15\22\1\0\3\22\17\0"+
    "\64\22\43\0\1\22\4\0\1\22\103\0\130\22\10\0\5\22\2\0"+
    "\42\22\1\0\1\22\5\0\106\22\12\0\37\22\61\0\36\22\2\0"+
    "\5\22\13\0\54\22\4\0\32\22\66\0\27\22\11\0\65\22\122\0"+
    "\1\22\135\0\57\22\21\0\7\22\67\0\36\22\15\0\2\22\12\0"+
    "\54\22\32\0\44\22\51\0\3\22\12\0\44\22\2\0\11\22\140\0"+
    "\4\22\1\0\4\22\3\0\2\22\11\0\300\22\100\0\u0116\22\2\0"+
    "\6\22\2\0\46\22\2\0\6\22\2\0\10\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\37\22\2\0\65\22\1\0\7\22\1\0"+
    "\1\22\3\0\3\22\1\0\7\22\3\0\4\22\2\0\6\22\4\0"+
    "\15\22\5\0\3\22\1\0\7\22\53\0\1\41\1\41\107\0\1\22"+
    "\15\0\1\22\20\0\15\22\145\0\1\22\4\0\1\22\2\0\12\22"+
    "\1\0\1\22\3\0\5\22\6\0\1\22\1\0\1\22\1\0\1\22"+
    "\1\0\4\22\1\0\13\22\2\0\4\22\5\0\5\22\4\0\1\22"+
    "\64\0\2\22\u0a7b\0\57\22\1\0\57\22\1\0\205\22\6\0\4\22"+
    "\3\0\2\22\14\0\46\22\1\0\1\22\5\0\1\22\2\0\70\22"+
    "\7\0\1\22\20\0\27\22\11\0\7\22\1\0\7\22\1\0\7\22"+
    "\1\0\7\22\1\0\7\22\1\0\7\22\1\0\7\22\1\0\7\22"+
    "\120\0\1\22\u01d5\0\2\22\52\0\5\22\5\0\2\22\4\0\126\22"+
    "\6\0\3\22\1\0\132\22\1\0\4\22\5\0\51\22\3\0\136\22"+
    "\21\0\33\22\65\0\20\22\u0200\0\u19b6\22\112\0\u51d6\22\52\0\u048d\22"+
    "\103\0\56\22\2\0\u010d\22\3\0\20\22\12\0\2\22\24\0\57\22"+
    "\20\0\37\22\2\0\106\22\61\0\11\22\2\0\147\22\2\0\44\22"+
    "\1\0\10\22\77\0\13\22\1\0\3\22\1\0\4\22\1\0\27\22"+
    "\35\0\64\22\16\0\62\22\76\0\6\22\3\0\1\22\1\0\1\22"+
    "\14\0\34\22\12\0\27\22\31\0\35\22\7\0\57\22\34\0\1\22"+
    "\20\0\5\22\1\0\12\22\12\0\5\22\1\0\51\22\27\0\3\22"+
    "\1\0\10\22\24\0\27\22\3\0\1\22\3\0\62\22\1\0\1\22"+
    "\3\0\2\22\2\0\5\22\2\0\1\22\1\0\1\22\30\0\3\22"+
    "\2\0\13\22\7\0\3\22\14\0\6\22\2\0\6\22\2\0\6\22"+
    "\11\0\7\22\1\0\7\22\1\0\53\22\1\0\12\22\12\0\163\22"+
    "\35\0\u2ba4\22\14\0\27\22\4\0\61\22\u2104\0\u016e\22\2\0\152\22"+
    "\46\0\7\22\14\0\5\22\5\0\1\22\1\0\12\22\1\0\15\22"+
    "\1\0\5\22\1\0\1\22\1\0\2\22\1\0\2\22\1\0\154\22"+
    "\41\0\u016b\22\22\0\100\22\2\0\66\22\50\0\14\22\164\0\5\22"+
    "\1\0\207\22\44\0\32\22\6\0\32\22\13\0\131\22\3\0\6\22"+
    "\2\0\6\22\2\0\6\22\2\0\3\22\43\0\14\22\1\0\32\22"+
    "\1\0\23\22\1\0\2\22\1\0\17\22\2\0\16\22\42\0\173\22"+
    "\u0185\0\35\22\3\0\61\22\57\0\40\22\20\0\21\22\1\0\10\22"+
    "\6\0\46\22\12\0\36\22\2\0\44\22\4\0\10\22\60\0\236\22"+
    "\22\0\44\22\4\0\44\22\4\0\50\22\10\0\64\22\234\0\u0137\22"+
    "\11\0\26\22\12\0\10\22\230\0\6\22\2\0\1\22\1\0\54\22"+
    "\1\0\2\22\3\0\1\22\2\0\27\22\12\0\27\22\11\0\37\22"+
    "\101\0\23\22\1\0\2\22\12\0\26\22\12\0\32\22\106\0\70\22"+
    "\6\0\2\22\100\0\1\22\17\0\4\22\1\0\3\22\1\0\33\22"+
    "\54\0\35\22\3\0\35\22\43\0\10\22\1\0\34\22\33\0\66\22"+
    "\12\0\26\22\12\0\23\22\15\0\22\22\156\0\111\22\67\0\63\22"+
    "\15\0\63\22\u0310\0\65\22\113\0\55\22\40\0\31\22\32\0\44\22"+
    "\51\0\43\22\3\0\1\22\14\0\60\22\16\0\4\22\25\0\1\22"+
    "\1\0\1\22\43\0\22\22\1\0\31\22\124\0\7\22\1\0\1\22"+
    "\1\0\4\22\1\0\17\22\1\0\12\22\7\0\57\22\46\0\10\22"+
    "\2\0\2\22\2\0\26\22\1\0\7\22\1\0\2\22\1\0\5\22"+
    "\3\0\1\22\22\0\1\22\14\0\5\22\236\0\65\22\22\0\4\22"+
    "\65\0\60\22\24\0\2\22\1\0\1\22\270\0\57\22\51\0\4\22"+
    "\44\0\60\22\24\0\1\22\73\0\53\22\125\0\32\22\u0186\0\100\22"+
    "\37\0\1\22\u01c0\0\71\22\u0107\0\11\22\1\0\45\22\21\0\1\22"+
    "\61\0\36\22\u0370\0\u039a\22\346\0\304\22\u0abc\0\u042f\22\u0fd1\0\u0247\22"+
    "\u21b9\0\u0239\22\7\0\37\22\161\0\36\22\22\0\60\22\20\0\4\22"+
    "\37\0\25\22\5\0\23\22\u0370\0\105\22\13\0\1\22\102\0\15\22"+
    "\100\0\1\22\37\0\u17ed\22\23\0\u02f3\22\u250d\0\2\22\u0bfe\0\153\22"+
    "\5\0\15\22\3\0\11\22\7\0\12\22\u1766\0\125\22\1\0\107\22"+
    "\1\0\2\22\2\0\1\22\2\0\2\22\2\0\4\22\1\0\14\22"+
    "\1\0\1\22\1\0\7\22\1\0\101\22\1\0\4\22\2\0\10\22"+
    "\1\0\7\22\1\0\34\22\1\0\4\22\1\0\5\22\1\0\1\22"+
    "\3\0\7\22\1\0\u0154\22\2\0\31\22\1\0\31\22\1\0\37\22"+
    "\1\0\31\22\1\0\37\22\1\0\31\22\1\0\37\22\1\0\31\22"+
    "\1\0\37\22\1\0\31\22\1\0\10\22\u1034\0\305\22\73\0\104\22"+
    "\u04bc\0\4\22\1\0\33\22\1\0\2\22\1\0\1\22\2\0\1\22"+
    "\1\0\12\22\1\0\4\22\1\0\1\22\1\0\1\22\6\0\1\22"+
    "\4\0\1\22\1\0\1\22\1\0\1\22\1\0\3\22\1\0\2\22"+
    "\1\0\1\22\2\0\1\22\1\0\1\22\1\0\1\22\1\0\1\22"+
    "\1\0\1\22\1\0\2\22\1\0\1\22\2\0\4\22\1\0\7\22"+
    "\1\0\4\22\1\0\4\22\1\0\1\22\1\0\12\22\1\0\21\22"+
    "\5\0\3\22\1\0\5\22\1\0\21\22\u1144\0\ua6d7\22\51\0\u1035\22"+
    "\13\0\336\22\2\0\u1682\22\u295e\0\u021e\22\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\4\3\1\1"+
    "\1\5\2\4\1\5\4\3\1\5\1\6\2\0\1\2"+
    "\1\0\4\3\2\0\1\7\1\10\1\3\1\11\2\3"+
    "\1\0\1\2\4\3\2\0\2\3\1\12\2\0\1\2"+
    "\1\3\1\13\2\3\2\14\1\2\1\0\1\3\1\15"+
    "\1\16\1\17\1\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\44\0\u018c\0\u01b0\0\220\0\u01d4"+
    "\0\u01f8\0\u021c\0\u0240\0\u0264\0\44\0\u0288\0\264\0\44"+
    "\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\u033c\0\u0360\0\u0384\0\220"+
    "\0\220\0\u03a8\0\154\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c"+
    "\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558\0\154"+
    "\0\u057c\0\u05a0\0\154\0\u05c4\0\154\0\u05e8\0\u060c\0\44"+
    "\0\u0630\0\u0654\0\u0654\0\u0678\0\154\0\154\0\44\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\2\1\4"+
    "\1\7\1\10\1\11\1\12\1\13\2\3\1\14\1\15"+
    "\1\16\1\4\1\5\1\17\2\4\1\20\2\4\1\21"+
    "\1\22\1\4\1\23\1\24\2\25\1\0\2\25\45\0"+
    "\1\3\1\26\1\4\3\0\5\4\1\0\2\3\3\0"+
    "\1\4\2\0\11\4\7\0\1\4\1\0\1\4\3\0"+
    "\5\4\1\0\2\4\3\0\1\4\2\0\11\4\12\0"+
    "\1\5\13\0\2\5\1\0\2\5\17\0\5\27\1\30"+
    "\1\31\35\27\1\0\1\4\1\0\1\4\3\0\4\4"+
    "\1\32\1\0\2\4\3\0\1\4\2\0\11\4\7\0"+
    "\1\4\1\0\1\4\3\0\5\4\1\0\2\4\3\0"+
    "\1\4\2\0\1\33\10\4\7\0\1\4\1\0\1\4"+
    "\3\0\5\4\1\0\2\4\3\0\1\4\2\0\3\4"+
    "\1\34\5\4\7\0\1\4\1\0\1\4\3\0\5\4"+
    "\1\0\2\4\3\0\1\4\2\0\2\4\1\35\6\4"+
    "\6\0\6\36\1\37\5\36\1\0\27\36\4\0\1\5"+
    "\13\0\1\40\1\5\1\0\2\5\23\0\1\5\13\0"+
    "\1\5\1\41\1\0\2\5\20\0\1\4\1\0\1\4"+
    "\3\0\5\4\1\0\2\4\3\0\1\4\2\0\1\4"+
    "\1\42\7\4\7\0\1\4\1\0\1\4\3\0\3\4"+
    "\1\43\1\4\1\0\2\4\3\0\1\4\2\0\11\4"+
    "\7\0\1\4\1\0\1\4\3\0\5\4\1\0\2\4"+
    "\3\0\1\4\2\0\7\4\1\44\1\4\7\0\1\4"+
    "\1\0\1\4\3\0\5\4\1\0\2\4\3\0\1\4"+
    "\2\0\3\4\1\45\5\4\44\0\1\46\6\0\1\47"+
    "\13\0\2\47\32\0\12\27\26\0\1\4\1\0\1\4"+
    "\3\0\5\4\1\0\2\4\3\0\1\4\2\0\1\50"+
    "\10\4\7\0\1\4\1\0\1\4\3\0\5\4\1\0"+
    "\2\4\3\0\1\4\2\0\1\4\1\51\7\4\7\0"+
    "\1\4\1\0\1\4\3\0\5\4\1\0\2\4\3\0"+
    "\1\4\2\0\1\4\1\52\7\4\7\0\1\4\1\0"+
    "\1\4\3\0\1\4\1\53\3\4\1\0\2\4\3\0"+
    "\1\4\2\0\11\4\22\0\1\30\34\0\10\36\1\54"+
    "\1\55\26\0\1\4\1\0\1\4\3\0\5\4\1\0"+
    "\2\4\3\0\1\4\2\0\4\4\1\56\4\4\7\0"+
    "\1\4\1\0\1\4\3\0\5\4\1\0\2\4\3\0"+
    "\1\4\2\0\5\4\1\57\3\4\7\0\1\4\1\0"+
    "\1\4\3\0\4\4\1\60\1\0\2\4\3\0\1\4"+
    "\2\0\11\4\44\0\1\61\6\0\1\47\1\0\1\62"+
    "\11\0\2\47\10\0\1\62\15\0\1\4\1\0\1\4"+
    "\3\0\5\4\1\0\2\4\3\0\1\4\2\0\2\4"+
    "\1\63\6\4\7\0\1\4\1\0\1\4\3\0\5\4"+
    "\1\0\2\4\3\0\1\4\2\0\1\4\1\63\7\4"+
    "\7\0\1\4\1\0\1\4\3\0\5\4\1\0\2\4"+
    "\3\0\1\4\2\0\4\4\1\50\4\4\7\0\1\4"+
    "\1\0\1\4\3\0\5\4\1\0\2\4\3\0\1\4"+
    "\2\0\1\64\10\4\22\0\1\30\2\55\41\0\1\30"+
    "\2\36\26\0\1\4\1\0\1\4\3\0\5\4\1\0"+
    "\2\4\3\0\1\4\2\0\2\4\1\65\2\4\1\66"+
    "\3\4\7\0\1\4\1\0\1\4\3\0\5\4\1\0"+
    "\2\4\3\0\1\4\2\0\1\4\1\67\7\4\6\0"+
    "\37\61\1\70\1\71\2\70\1\61\1\0\1\72\2\0"+
    "\1\73\10\0\2\72\26\0\1\4\1\0\1\4\3\0"+
    "\4\4\1\74\1\0\2\4\3\0\1\4\2\0\11\4"+
    "\7\0\1\4\1\0\1\4\3\0\3\4\1\75\1\4"+
    "\1\0\2\4\3\0\1\4\2\0\11\4\7\0\1\4"+
    "\1\0\1\4\3\0\5\4\1\0\2\4\3\0\1\4"+
    "\2\0\2\4\1\76\6\4\45\0\1\77\5\0\1\72"+
    "\13\0\2\72\26\0\1\4\1\0\1\4\3\0\2\4"+
    "\1\100\2\4\1\0\2\4\3\0\1\4\2\0\11\4"+
    "\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1692];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\1\11\10\1\1\11\2\0\1\11"+
    "\1\0\4\1\2\0\6\1\1\0\5\1\2\0\3\1"+
    "\2\0\5\1\1\11\2\1\1\0\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

public NanoMorphoParser yyparser;

public int getLine() { return yyline+1; }
public int getColumn() { return yycolumn+1; }

public NanoMorphoLexer(java.io.Reader r, NanoMorphoParser yyparser )
{
	this(r);
	this.yyparser = yyparser;
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NanoMorphoLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2442) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return NanoMorphoParser.YYERRCODE;
            } 
            // fall through
          case 17: break;
          case 2: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
	return NanoMorphoParser.LITERAL;
            } 
            // fall through
          case 18: break;
          case 3: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
	return NanoMorphoParser.NAME;
            } 
            // fall through
          case 19: break;
          case 4: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
	switch( yytext().charAt(0) )
	{
	case '^':
	case '?':
	case '~':
		return NanoMorphoParser.OP1;
	case ':':
		return NanoMorphoParser.OP2;
	case '|':
		return NanoMorphoParser.OP3;
	case '&':
		return NanoMorphoParser.OP4;
	case '!':
	case '=':
	case '<':
	case '>':
		return NanoMorphoParser.OP5;
	case '+':
	case '-':
		return NanoMorphoParser.OP6;
	case '*':
	case '/':
	case '%':
		return NanoMorphoParser.OP7;
	default:
		throw new Error("Invalid opname");
	}
            } 
            // fall through
          case 20: break;
          case 5: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
	return yycharat(0);
            } 
            // fall through
          case 21: break;
          case 6: 
            { 
            } 
            // fall through
          case 22: break;
          case 7: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
    return NanoMorphoParser.AND;
            } 
            // fall through
          case 23: break;
          case 8: 
            { yyparser.yylval = new NanoMorphoParserVal(yytext());
    return NanoMorphoParser.OR;
            } 
            // fall through
          case 24: break;
          case 9: 
            { return NanoMorphoParser.IF;
            } 
            // fall through
          case 25: break;
          case 10: 
            { return NanoMorphoParser.VAR;
            } 
            // fall through
          case 26: break;
          case 11: 
            { return NanoMorphoParser.ELSE;
            } 
            // fall through
          case 27: break;
          case 12: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { 
            } 
            // fall through
          case 28: break;
          case 13: 
            { return NanoMorphoParser.ELSIF;
            } 
            // fall through
          case 29: break;
          case 14: 
            { return NanoMorphoParser.WHILE;
            } 
            // fall through
          case 30: break;
          case 15: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { 
            } 
            // fall through
          case 31: break;
          case 16: 
            { return NanoMorphoParser.RETURN;
            } 
            // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
